# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Reference App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'TTTAttributedLabel', '~> 2.0'
	pod 'SLXMPPFramework', '~> 4.0'
	pod 'Promises', '~> 2.0'
	pod 'RNCryptor', '~> 5.0'
	pod 'ReachabilitySwift', '~> 4.3'

end
